# Generated by Django 4.2.14 on 2024-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('binary_encoding', models.BinaryField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudySessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
                ('noise_level', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
            ],
        ),
    ]
