# Generated by Django 4.2.14 on 2024-08-04 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_data', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('focus_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('binary_encoding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='StudySessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('noise_level', models.CharField(max_length=255)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
        ),
    ]
