# Generated by Django 4.1.13 on 2024-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='binary_encoding',
        ),
        migrations.AddField(
            model_name='images',
            name='b64_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
