# Generated by Django 4.2.14 on 2024-08-03 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessions',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysessions',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
