# Generated by Django 4.2.14 on 2024-08-03 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_studysessions_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_data',
            name='focus_level',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='binary_encoding',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
